apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: t2-only
spec:
  amiFamily: AL2
  instanceProfile: KarpenterNodeInstanceProfile
  subnetSelectorTerms:
    - tags:
        Name: eks-nodejs-eks-karpenter-subnet-public*
  securityGroupSelectorTerms:
    - tags:
        aws:eks:cluster-name: nodejs-eks-karpenter

