name: CI - Build and Push Docker Image

on:
  push:
    branches: [main]
    paths:
      - 'app/**'
      - 'Dockerfile'
      - 'docker-compose.yml'

env:
  IMAGE_TAG: v2
  DOCKER_IMAGE: aaleem1993/bootcamp-node-app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: npm ci
      working-directory: ./app

    - name: Run tests
      run: npm test || echo "Tests failed or skipped"
      working-directory: ./app

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker Image
      run: docker build -t $DOCKER_IMAGE:$IMAGE_TAG .

    - name: Tag as latest
      run: docker tag $DOCKER_IMAGE:$IMAGE_TAG $DOCKER_IMAGE:latest

    - name: Push Docker Image Tags
      run: |
        docker push $DOCKER_IMAGE:$IMAGE_TAG
        docker push $DOCKER_IMAGE:latest

